### ISSUE TITLE
A Way To Throttle Upload Limit

### ISSUE THREAD

**Issue by townsmcp** [doob187/traefikv2apps#27]
**Is your feature request related to a problem? Please describe.**
When Uploader is transfering content to Team Drive, Plex playback is jerky and freezing every few seconds, even at 720p playback. Plex also shows a message saying the network is to slow.

**Describe the solution you'd like**
What I would like is a way to limit upload speed. I have 1000Mb/sec download and 120Mb/sec upload FTTP and a way to be able to set the upload speed should resolve the problem (ie set to half the upload speed).

**Describe alternatives you've considered**
Where rclone.conf was copied from PGBliz, the rclone.conf file contains lines like:
```
service_account_file = /opt/appdata/plexguide/.blitzkeys/GDSA01
```
Should these lines be removed/repointed elsewhere?

I have dug around in the /opt/appdata/uploader/ files and can see in uploader.env there is a field:
```
BANDWITHLIMIT=null
```
Im wondering if a value was set here, would upload be limited? If so, is it in KB or MB?

**Comment by doob187** [comment]
You can change the values live 

```
cd /opt/appdata/uploader/env
sudo nano uploader.env
```

Reference >
```
https://rclone.org/docs/#bwlimit-bandwidth-spec
```

**Comment by townsmcp** [comment]
@doob187 thank you so much for all that.
Just in case anyone in else is interested, I went with the following line:
```
BANDWITHLIMIT="03:00,10M:off 08:00,5M:off"
```
This will set upload speed 10MBytes between 3:00am and 8:00am and then throttle speed to 5MBytes between 8:00am and 3:00am. Download speed is unrestricted
